In [23]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [24]:
data = pd.read_csv('04.reduced_telco_data.csv')
data.head()

SeniorCitizen    tenure  PhoneService  PaperlessBilling  MonthlyCharges  \
0              0 -0.244200             1                 1        0.021083   
1              1 -0.306748             1                 0        0.053733   
2              0 -0.744587             1                 0        0.004393   
3              0  1.069316             1                 1        0.020597   
4              0 -0.619490             1                 0        0.041444   

   TotalCharges  Churn  Contract_Month-to-Month  Contract_One year  \
0      0.001391      0                        1                  0   
1      0.002613      0                        0                  0   
2      0.000401      0                        0                  1   
3      0.002886      0                        0                  0   
4      0.001535      0                        1                  0   

   Contract_Two year  ...  DeviceProtection_Yes  TechSupport_No  \
0                  0  ...                     0               1   
1                  1  ...                     0               1   
2                  0  ...                     0               1   
3                  1  ...                     0               1   
4                  0  ...                     1               1   

   TechSupport_Unknown  TechSupport_Yes  StreamingTV_No  StreamingTV_Unknown  \
0                    0                0               0                    0   
1                    0                0               1                    0   
2                    0                0               1                    0   
3                    0                0               1                    0   
4                    0                0               1                    0   

   StreamingTV_Yes  StreamingMovies_No  StreamingMovies_Unknown  \
0                1                   0                        0   
1                0                   1                        0   
2                0                   1                        0   
3                0                   1                        0   
4                0                   1                        0   

   StreamingMovies_Yes  
0                    1  
1                    0  
2                    0  
3                    0  
4                    0  

[5 rows x 47 columns]

In [25]:
# # Assign X (all columns except 'Churn')
# X = data.drop(columns=['Churn'])

In [26]:
# # Assign Y (only 'Churn')
# Y = data['Churn']

In [27]:
# print("X shape:", X.shape)  
# X.head(2)

In [28]:
# print("Y shape:", Y.shape) 
# Y.head(2)

In [29]:
# # Train-test split (80% train, 20% test)
# X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42, stratify=Y)

In [30]:
# print("Train-test split done!")
# print("Train size:", X_train.shape, Y_train.shape)
# print("Test size:", X_test.shape, Y_test.shape)

In [31]:
# # Save them to train_test_split_dataset folder
# X_train.to_csv("../Train_test_dataset/X_train.csv", index=False)
# X_test.to_csv("../Train_test_dataset/X_test.csv", index=False)
# Y_train.to_csv("../Train_test_dataset/Y_train.csv", index=False)
# Y_test.to_csv("../Train_test_dataset/Y_test.csv", index=False)

In [32]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56000 entries, 0 to 55999
Data columns (total 47 columns):
 #   Column                                   Non-Null Count  Dtype  
---  ------                                   --------------  -----  
 0   SeniorCitizen                            56000 non-null  int64  
 1   tenure                                   56000 non-null  float64
 2   PhoneService                             56000 non-null  int64  
 3   PaperlessBilling                         56000 non-null  int64  
 4   MonthlyCharges                           56000 non-null  float64
 5   TotalCharges                             56000 non-null  float64
 6   Churn                                    56000 non-null  int64  
 7   Contract_Month-to-Month                  56000 non-null  int64  
 8   Contract_One year                        56000 non-null  int64  
 9   Contract_Two year                        56000 non-null  int64  
 10  PaymentMethod_Bank transfer (automatic)  56000

In [33]:
y = data.iloc[:,6].values
y

array([0, 0, 0, ..., 1, 1, 1], shape=(56000,))

In [34]:
tmp = data.drop(data.columns[6], axis=1)
X = tmp.iloc[:,:].values

In [35]:
X

array([[ 0.        , -0.2441996 ,  1.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 1.        , -0.30674798,  1.        , ...,  1.        ,
         0.        ,  0.        ],
       [ 0.        , -0.74458664,  1.        , ...,  1.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  0.6940261 ,  1.        , ...,  1.        ,
         0.        ,  0.        ],
       [ 0.        , -0.30674798,  1.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 0.        , -1.24497368,  1.        , ...,  1.        ,
         0.        ,  0.        ]], shape=(56000, 46))

In [36]:
import numpy as np
np.bincount(y) # *output-> [0 count, 1 count]

array([29762, 26238])

In [37]:
# split data to train and testing
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(
    X,y,
    test_size=0.8,
    random_state= 42,
    stratify=y,
)

In [38]:
X_train[1]

array([0.        , 1.13186476, 1.        , 1.        , 0.00743705,
       0.00176917, 0.        , 0.        , 1.        , 0.        ,
       0.        , 1.        , 0.        , 0.        , 1.        ,
       0.        , 1.        , 0.        , 0.        , 0.        ,
       0.        , 1.        , 0.        , 0.        , 1.        ,
       0.        , 1.        , 0.        , 1.        , 0.        ,
       0.        , 1.        , 0.        , 0.        , 0.        ,
       0.        , 1.        , 0.        , 1.        , 0.        ,
       0.        , 0.        , 1.        , 1.        , 0.        ,
       0.        ])

In [39]:
import numpy as np
import tensorflow as tf 
from tensorflow import keras

np.random.seed(42)
tf.random.set_seed(42)


In [64]:
X_train.shape[1]

46

In [40]:
model = keras.Sequential(
    [
        keras.layers.Input(shape=(X_train.shape[1],)),
        keras.layers.Dense(64, activation="selu"),
        keras.layers.BatchNormalization(),
        keras.layers.Dropout(0.2),
        keras.layers.Dense(32, activation="selu"),
        keras.layers.BatchNormalization(),
        keras.layers.Dropout(0.2),
        keras.layers.Dense(16, activation="selu"),
        keras.layers.BatchNormalization(),
        keras.layers.Dropout(0.2),
        keras.layers.Dense(1, activation="sigmoid"),
    ]
)

In [41]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 64)             │         3,008 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_3           │ (None, 64)             │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_4           │ (None, 32)             │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_5           │ (None, 16)             │            64 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 6,081 (23.75 KB)

 Trainable params: 5,857 (22.88 KB)

 Non-trainable params: 224 (896.00 B)

In [ ]:
model.compile(
    optimizer="nadam",
    loss="binary_crossentropy",
    metrics=[
        "accuracy",
        tf.keras.metrics.Precision(),
        tf.keras.metrics.Recall(),
        tf.keras.metrics.AUC(),  # Area Under the Curve (ROC)
    ],
)

In [43]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56000 entries, 0 to 55999
Data columns (total 47 columns):
 #   Column                                   Non-Null Count  Dtype  
---  ------                                   --------------  -----  
 0   SeniorCitizen                            56000 non-null  int64  
 1   tenure                                   56000 non-null  float64
 2   PhoneService                             56000 non-null  int64  
 3   PaperlessBilling                         56000 non-null  int64  
 4   MonthlyCharges                           56000 non-null  float64
 5   TotalCharges                             56000 non-null  float64
 6   Churn                                    56000 non-null  int64  
 7   Contract_Month-to-Month                  56000 non-null  int64  
 8   Contract_One year                        56000 non-null  int64  
 9   Contract_Two year                        56000 non-null  int64  
 10  PaymentMethod_Bank transfer (automatic)  56000

In [44]:
early_stopping = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience = 1000, restore_best_weights = True)
history = model.fit(
    X_train , y_train ,
    epochs = 200,
    batch_size = 4,
    validation_split = 0.2,
    verbose = 1,
    callbacks=[early_stopping]
)

Epoch 1/200
2240/2240 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.6518 - auc_1: 0.6909 - loss: 0.6615 - precision_1: 0.6260 - recall_1: 0.6275 - val_accuracy: 0.7589 - val_auc_1: 0.7725 - val_loss: 0.5380 - val_precision_1: 0.6990 - val_recall_1: 0.8723
Epoch 2/200
2240/2240 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.7020 - auc_1: 0.7548 - loss: 0.5853 - precision_1: 0.6704 - recall_1: 0.7090 - val_accuracy: 0.7594 - val_auc_1: 0.7686 - val_loss: 0.5381 - val_precision_1: 0.6987 - val_recall_1: 0.8751
Epoch 3/200
2240/2240 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.7108 - auc_1: 0.7622 - loss: 0.5760 - precision_1: 0.6745 - recall_1: 0.7332 - val_accuracy: 0.7589 - val_auc_1: 0.7741 - val_loss: 0.5389 - val_precision_1: 0.6984 - val_recall_1: 0.8742
Epoch 4/200
2240/2240 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.7172 - auc_1: 0.7674 - loss: 0.5700 - precision_1: 0.6802 - recall_1: 0.7418 - val_accuracy: 0.7589 - val_auc_1: 0.7720 - val_loss: 0.5398 - val_precision_1: 0.

In [51]:
loss, accuracy, precision, recall, auc=model.evaluate(
    X_test,y_test
)


1400/1400 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.7692 - auc_1: 0.7913 - loss: 0.5194 - precision_1: 0.6991 - recall_1: 0.8907


In [53]:
print(f"loss \t\t : {loss}")
print(f"accuracy \t : {accuracy}")
print(f"precision \t : {precision}")
print(f"recall \t\t : {recall}")
print(f"auc \t\t : {auc}")

loss 		 : 0.5194490551948547
accuracy 	 : 0.7691740989685059
precision 	 : 0.6991137266159058
recall 		 : 0.8906621932983398
auc 		 : 0.7913320064544678


Certainly! Here is a table summarizing the five evaluation metrics for binary classification models, their purpose, and what their values mean.

| Metric | Purpose / What It Measures | Calculation | Interpretation |
| :--- | :--- | :--- | :--- |
| **Loss** (Binary Cross-Entropy) | Measures the **error** between the predicted probabilities and the true labels. The value the model tries to minimize. | Based on the natural logarithm of predicted probabilities. | **Lower is better** (closer to $0.0$). A high value means the model is confidently wrong often. |
| **Accuracy** | Measures the proportion of **total predictions** that were correct (both positive and negative). | $\frac{\text{TP} + \text{TN}}{\text{Total Samples}}$ | General measure of correctness. Can be misleading with imbalanced data. |
| **Precision** | Measures the confidence of **positive predictions**. "Of all predicted positive cases, how many were actually positive?" | $\frac{\text{True Positives}}{\text{True Positives} + \text{False Positives}}$ | **Higher is better.** Prioritized when **False Alarms** (False Positives) are costly. |
| **Recall** | Measures the model's ability to **find all positive cases**. "Of all actual positive cases, how many were correctly identified?" | $\frac{\text{True Positives}}{\text{True Positives} + \text{False Negatives}}$ | **Higher is better.** Prioritized when **Missing a case** (False Negatives) is costly. |
| **AUC** (Area Under the ROC Curve) | Measures the **overall model quality** across all possible thresholds, particularly useful for imbalanced data. | Probability of correctly ranking a random positive case higher than a random negative case. | Ranges from $0.5$ (random) to $1.0$ (perfect). **Higher is better.** |

*(Note: TP = True Positives, TN = True Negatives, FP = False Positives, FN = False Negatives)*

In [58]:
y_pred_prob = model.predict(X_test)
y_pred_prob

1400/1400 ━━━━━━━━━━━━━━━━━━━━ 1s 774us/step


array([[0.7049635 ],
       [0.7478007 ],
       [0.7057483 ],
       ...,
       [0.06398952],
       [0.8399402 ],
       [0.7555299 ]], shape=(44800, 1), dtype=float32)

In [59]:
y_pred = (y_pred_prob >= 0.5).astype(int) # to addjest to the recall and the precision can adjest thie threshold. but adjestion this can get tradeoffs. edit with caution.
print(y_pred[:10])

[[1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]]


In [61]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[15764,  8046],
       [ 2295, 18695]])

The code you provided uses the `confusion_matrix` function from the `sklearn.metrics` module to generate a **Confusion Matrix**.

This matrix is a table that summarizes the performance of your classification model by comparing the model's binary predictions (`y_pred`) against the actual true labels (`y_test`). It is the foundation for calculating metrics like Precision and Recall.

***

## What the Confusion Matrix Does

The Confusion Matrix breaks down your model's predictions into four distinct categories:

| | **Predicted: No Churn (0)** | **Predicted: Churn (1)** |
| :--- | :--- | :--- |
| **Actual: No Churn (0)** | **True Negative (TN)** | **False Positive (FP)** |
| **Actual: Churn (1)** | **False Negative (FN)** | **True Positive (TP)** |

### Explanation of the Four Components:

1.  **True Positive (TP):** The model correctly predicted Churn (1) when the customer **actually churned** (1). (Good)
2.  **True Negative (TN):** The model correctly predicted No Churn (0) when the customer **actually stayed** (0). (Good)
3.  **False Positive (FP):** The model predicted Churn (1) when the customer **actually stayed** (0). This is a **False Alarm**. (Bad)
4.  **False Negative (FN):** The model predicted No Churn (0) when the customer **actually churned** (1). This is a **Missed Opportunity**. (Bad)

## Example Output

When you run `confusion_matrix(y_test, y_pred)`, the output (using scikit-learn's standard format) will look like this, where the labels are organized as `[TN, FP], [FN, TP]`:

$$\begin{bmatrix} TN & FP \\ FN & TP \end{bmatrix}$$

For instance, if the output is:

$$\begin{bmatrix} 900 & 100 \\ 50 & 150 \end{bmatrix}$$

It means:

* **900** customers were correctly predicted to stay (TN).
* **100** customers were falsely predicted to churn (FP - False Alarms).
* **50** customers were missed (FN - Missed Churners).
* **150** customers were correctly predicted to churn (TP).

This matrix gives you the raw counts needed to calculate all your key metrics: Precision, Recall, and Accuracy.

`Saving the model`

In [63]:
model_filename = 'telco_churn_prediction_model_V1.0.keras'
# Save the entire model
model.save(model_filename) 

print(f"Model saved successfully as {model_filename}")

Model saved successfully as telco_churn_prediction_model_V1.0.keras
